#!/bin/bash
# Lista de parâmetros da interface
# $1 -> usuário

if [[ "$1" == 'root' ]]; then
	gateway="$(route -n | awk '{print $2}' | sed '3!d')"
	echo "Gateway do host: $gateway"
	argumentosARP="$(arp -n | awk '{print $5, $1, $3}'|grep "$gateway")"
	sudo arp -s -i $argumentosARP
else
	echo -e "\033[01mApenas o root pode executar esta função\033[0m"
fi
