#!/bin/bash

installChk(){
	wget http://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.8rel.2.tar.gz
	tar -xf lynx2.8.8rel.2.tar.gz
	cd lynx-2.8.8
	sudo ./configure && sudo make && sudo make install
	cd ..
	rm -rf lynx-2.8.8 lynx2.8.8rel.2.tar.gz
}

checkLynx(){
	checagem="$(which lynx)"
	if [[ "$checagem" == "" ]]; then
		installChk
	fi
}
