#!/bin/bash
# Variável 'busca' faz a busca de todos os argumentos passados após o nome
# do módulo chamado pelo programa principal
path="$1"
full="$*"
busca="$(echo "${full[@]:1}")"

# Caso busca seja vazia, irá insistir até que não seja
while [ "$busca" == "" ]; do
  echo -e "Cidades necessita de um elemento para busca, por favor informe"
  echo -n ">_ "
  read busca
done

busca=$(echo $busca|sed 'y/áÁàÀãÃâÂéÉêÊíÍõÕóÓôÔúÚçÇ/aAaAaAaAeEeEiIoOoOoOuUcC/')

cidades_num="$(wc -l "$path"database/cidades|cut -d " " -f1)"
echo -e "Contei $cidades_num cidades brasileiras, ao total."

cidadeSearch=$(sed 'y/áÁàÀãÃâÂéÉêÊíÍõÕóÓôÔúÚçÇ/aAaAaAaAeEeEiIoOoOoOuUcC/' "$path"database/cidades | grep -i "$busca" --color|wc -l|cut -d " " -f1)
echo -e "Sua busca teve $cidadeSearch resultados\n"
read -p "Pressione enter para ver sua busca [$busca]..."
sed 'y/áÁàÀãÃâÂéÉêÊíÍõÕóÓôÔúÚçÇ/aAaAaAaAeEeEiIoOoOoOuUcC/' "$path"database/cidades | grep -i "$busca" --color
