#!/bin/bash
# Exigido apenas o número de CPF

cpf="$1"
nomePessoa=$(curl -s 'http://cpfhunter.pe.hu' --data "nDoc=$cpf&proxy=1" |
grep '<nome>' | sed 's/<[^>]*>//g' | cut -d ':' -f2 | sed 's/^ *//g'|
tr A-Z a-z | sed 's/ ./\U&/g; s/^./\U&/g')

echo "Nome da pessoa: $nomePessoa"
