#!/bin/bash
for palavra in $*; do
  string=( ${string[@]} "$palavra")
done
parametros=${string[@]:0}

file=$(echo "$parametros"|tr " " "\n"|grep -A 1 -w "\-f"|tail -1)
if [[ "$file" == "" ]]; then
  file=$(echo "$parametros" |tr " " "\n" | grep -A 1 -w "\-\-file" | tail -1)
fi
if [[ "$file" == "" ]]; then
  read -p "Informe onde será criado o arquivo: " file
fi

extension=$(echo "$parametros"|tr " " "\n"|grep -A 1 -w "\-e"|tail -1)
if [[ "$extension" == "" ]]; then
  extension=$(echo "$parametros" |tr " " "\n" | grep -A 1 -w "\-\-extensao" | tail -1)
fi
if [[ "$extension" == "" ]]; then
  read -p "Informa a extensão do arquivo a ser criado: " extension
fi
extension=$(echo $extension|tr -d '.')
file=$(echo $file|tr -d '.')

createFiles(){
  if [[ "$extension" == "html" ]]; then
    echo "<html>
    <head>
      <meta charset='utf-8'>
      <title>$file</title>
      <meta http-equiv='X-UA-Compatible' content='IE=edge'>
      <meta name='viewport' content='width=device-width, initial-scale=1'>
      <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
      <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
      <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
    </head>
    <body>
      <nav class='navbar navbar-default'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
              <span class='sr-only'>Toggle navigation</span>
              <span class='icon-bar'></span> <span class='icon-bar'></span> <span class='icon-bar'></span>
            </button>
            <a class='navbar-brand' href='#'>Brand</a>
          </div>

          <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
            <ul class='nav navbar-nav'>
              <li class='active'><a href='#'>Link <span class='sr-only'>(current)</span></a></li>
              <li><a href='#'>Link</a></li>
              <li class='dropdown'>
                <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Dropdown <span class='caret'></span></a>
                <ul class='dropdown-menu'>
                  <li><a href='#'>Action</a></li>
                  <li><a href='#'>Another action</a></li>
                  <li><a href='#'>Something else here</a></li>
                  <li role='separator' class='divider'></li>
                  <li><a href='#'>Separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class='navbar-form navbar-left'>
              <div class='form-group'>
                <input type='text' class='form-control' placeholder='Search'>
              </div>
              <button type='submit' class='btn btn-default'>Submit</button>
            </form>
            <ul class='nav navbar-nav navbar-right'>
              <li><a href='#'>Link</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <div class='conteiner-fluid'>
      <h1>Hello Hacker</h1>
    </div>
    <footer>
      <h2>Footer</h2>
    </footer>
    </body>
  </html>"

  elif [[ "$extension" == "php" ]]; then
    echo "<?php
      echo date('d/i/y').'<br>';
      echo \$_SERVER['REMOTE_ADDR']; ?>"

  elif [[ "$extension" == "python" ]] || [[ "$extension" == "py" ]]; then
    echo "#!$(which python)
# coding: utf-8
import sys
programa = sys.argv[0]
argumentos = sys.argv[1:len(sys.argv)]
print (argumentos)"
  elif [[ "$extension" == "c" ]] || [[ "$extension" == ".c" ]];then
    echo "#include <stdio.h>
    #include <stdlib.h>
    #include <time.h>
    #include <math.h>
    #define pi 3.141592

    void main(int argc, char *argv){
      printf("\\nHelloWorld\\n");
    }"
  fi
}
touch "${file}.${extension}"

echo "${file}.${extension}"
createFiles > "${file}.${extension}"
