#!/bin/bash
# Recovery de senha no mysql, usando systemctl
# Todos os argumentos passados são convertidos para a senha
# Espaços são deletados da string
for palavra in $*; do
  string=( ${string[@]} "$palavra")
done
parametros=${string[@]:0}

password=$(echo "$parametros"|tr -d " ")
while [[ "$password" == "" ]]; do
  read -p "Informe a senha do DB: " password
done

systemctl stop mysql
systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
systemctl start mysqld

echo "UPDATE mysql.user SET authentication_string = PASSWORD('$password')
    -> WHERE User = 'root' AND Host = 'localhost';" | mysql -u root
echo "FLUSH PRIVILEGES;" | mysql -u root

systemctl stop mysql
systemctl unset-environment MYSQLD_OPTS
systemctl start mysql

mysql -u root -p$password
