#!/bin/bash
# Desenvolvedor: vandalvnl
# GitHub: github.com/vandalvnl
# Refatorando o código da versão Alpha de mia, até hoje presente em
# github.com/vandalvnl/mia
# Nesta versão, procuro refatorar todo o código e garantir maior usabilidade
# e desempenho ao usuário

banner(){
  echo '     --------------------------------------
    |  ____    ____   _____        _       |
    | |_   \  /   _| |_   _|      / \      |
    |   |   \/   |     | |       / _ \     |
    |   | |\  /| |     | |      / ___ \    |
    |  _| |_\/_| |_   _| |_   _/ /   \ \_  |
    | |_____||_____| |_____| |____| |____| |
    |                                      |
    |    Minha Inteligência Artificial     |
     --------------------------------------
 '
}
menuajuda(){
  bash "$whereMia"database/hello "$nome" && exit
}
openTODO(){
  $browser "$whereMia"/database/readme.md
}
getExecMiaPath(){
  whereMia=$(echo "$0"|sed 's/^ \+//'|sed 's@./@&\n@g;'|sed '$d'|tr -d '\n')
  if [[ "$whereMia" == "./" ]]; then
    whereMia=""
  fi
}

getNome(){
  nome="$(cat ${whereMia}consciencia.conf|sed 's/^ \+//'|grep -iw ^"_nome"|tr "\t" " " |sed 's/_nome//g;
  s/[ ]\+/ /g;s/^ //g')"
}

getPath(){
  path="$(cat ${whereMia}consciencia.conf|sed 's/^ \+//'|grep -iw ^"_pathsave"|tr "\t" " " |sed 's/_pathsave//g;
  s/[ ]\+/ /g;s/^ //g')"
}

getEditor(){
  editor="$(cat ${whereMia}consciencia.conf|sed 's/^ \+//'|grep -iw ^"_editor"|tr "\t" " " |sed 's/_editor//g;
  s/[ ]\+/ /g;s/^ //g')"
}

getExecType(){
  execType="$(cat ${whereMia}consciencia.conf|sed 's/^ \+//'|grep -iw ^"_executar"|tr "\t" " "|sed 's/_executar//g;
  s/[ ]\+/ /g;s/^ //g')"
}

getBrowser(){
  browser="$(cat ${whereMia}consciencia.conf|sed 's/^ \+//'|grep -iw ^"_browser"|tr "\t" " " |sed 's/_browser//g;
  s/[ ]\+/ /g;s/^ //g')"
}

getUsuario(){
  usuario="$(whoami)"
}

getParametros(){
  argLen="${2-#}"
  for palavra in $*; do
    string=( ${string[@]} "$palavra")
  done
  parametros=${string[@]:1}
  export parametros
}

getNetInterfaces(){
  interface=$(ifconfig|egrep -io ^'\w+'|sed '/lo/d')
}

setIPAddr(){
  if [[ "$1" == "wan" ]]; then
    bash ${whereMia}conteiner/ipAddr 'wan' $path
    return 1
  fi
  getNetInterfaces
  > $path/interfaces
  bash ${whereMia}conteiner/ipAddr 'lan' "$path"
  if [[ $(cat $path/interfaces) != "" ]]; then
    echo "Endereço IP:" && cat $path/interfaces
  fi
}

getSorte(){
  sorte=$(echo $(($RANDOM%RANDOM%2)))
  if [[ "$sorte" == "0" ]]; then
    echo "Coroa"
  else
    echo "Cara"
  fi
}

interacoes(){
  bash "${whereMia}"conteiner/conversas "$*"
}

execFunctions(){
  chmod +x "${whereMia}"conteiner/* -R -f
  if [[ "$1" == "" ]] || [[ "$1" == "help" ]] || [[ "$1" == "ola" ]]; then
    menuajuda ;
  fi
  if [[ "$1" == "hash" ]] || [[ "$1" == "compare" ]]; then
    bash "${whereMia}"conteiner/compare "$whereMia" "$parametros"
  elif [[ "$1" == "wan" ]] || [[ "$1" == "ipext" ]]; then
    setIPAddr wan

  elif [[ "$1" == "tempo" ]] || [[ "$1" == "data" ]]; then
    bash "${whereMia}"conteiner/tempo

  elif [[ "$1" == "cpf" ]]; then
    bash "${whereMia}"conteiner/cpf $parametros

  elif [[ "$1" == "css" ]] || [[ "$1" == "revminifier" ]]; then
    bash "${whereMia}"conteiner/cssrefix $parametros

  elif [[ "$1" == "cara" ]] || [[ "$1" == "coroa" ]]; then
    getSorte

  elif [[ "$1" == "lan" ]] || [[ "$1" == "ip" ]]; then
    setIPAddr "$path"

  elif [[ "$1" == "install" ]] || [[ "$1" == "mia" ]] || [[ "$1" == "instalar" ]]; then
    bash "${whereMia}"conteiner/chkMia "$whereMia"

  elif [[ "$1" == "footprint" ]] || [[ "$1" == "scan" ]]; then
    cp "${whereMia}"database/nmpstl.xsl "$path"/xmlstyle.xsl
    bash "${whereMia}"conteiner/scan "$browser" "$path" "$whereMia" $parametros

  elif [[ "$1" == "cep" ]] || [[ "$1" == "localiza" ]]; then
    bash "${whereMia}"conteiner/cep "$path" "$2"

  elif [[ "$1" == "inverte" ]] || [[ "$1" == "reverso" ]]; then
    echo -n ">_ "
    echo -n "$parametros" | sed 's/^/§ /;:a;s/\(.*\)§ \+\([^ ]\+\)/\2 \1§/;ta;s/§//'

  elif [[ "$1" == "cidades" ]] || [[ "$1" == "cidade" ]]; then
    bash "${whereMia}"conteiner/cidades "${whereMia}" "$parametros"

  elif [[ "$1" == "rename" ]] || [[ "$1" == "extensao" ]]; then
    bash "${whereMia}"conteiner/extrename "${whereMia}" $parametros

  elif [[ "$1" == "cria" ]] || [[ "$1" == "create" ]]; then
    bash "${whereMia}"conteiner/create "${whereMia}" $parametros

  elif [[ "$1" == "arpfix" ]] || [[ "$1" == "arp" ]]; then
    setIPAddr "$path"
    bash "${whereMia}"conteiner/arpfix "$usuario"

  elif [[ "$1" == "swap" ]] || [[ "$1" == "swappiness" ]]; then
    bash "${whereMia}"conteiner/swap "$usuario" $parametros

  elif [[ "$1" == "sql" ]] || [[ "$1" == "database" ]]; then
    bash "${whereMia}"conteiner/sqlrecovery $parametros

  elif [[ "$1" == "macchange" ]] || [[ "$1" == "spoof" ]]; then
    setIPAddr "$path" > "$path"/interfacerede
    interfaces=$(cat "$path"/interfacerede | cut -d ' ' -f1 | tr -d ':'|tr '\n' ' ')
    bash "${whereMia}"conteiner/spoof $interfaces

  elif [[ "$1" == "mac" ]] || [[ "$1" == "macsearch" ]]; then
    bash "${whereMia}"conteiner/macsearch "$path" "${whereMia}" "$parametros"

  elif [[ "$1" == "--nome" ]] || [[ "$1" == "-n" ]]; then
    sed -i "s/^ \+//g; /^_nome/s/.*/_nome $parametros/" "${whereMia}"consciencia.conf && getNome
    echo -e "Seu nome foi alterado para $nome"

  elif [[ "$1" == "--editor" ]] || [[ "$1" == "-e" ]]; then
    sed -i "s/^ \+//g; /^_editor/s/.*/_editor $parametros/" "${whereMia}"consciencia.conf && getEditor
    echo -e "Seu editor foi alterado para $editor"

  elif [[ "$1" == "--browser" ]] || [[ "$1" == "-b" ]]; then
    sed -i "s/^ \+//g; /^_browser/s/.*/_browser $parametros/" "${whereMia}"consciencia.conf && getBrowser
    echo -e "Seu editor foi alterado para $browser"

  elif [[ "$1" == "--config" ]] || [[ "$1" == "-c" ]]; then
    echo "Seu nome: $nome"
    echo "Seu usuário: $usuario"
    echo "Seu browser: $browser"
    echo "Seu editor de texto: $editor"
    bash "${whereMia}"conteiner/chkMia "$whereMia"

  elif [[ "$1" == "calc" ]]; then
    python3 "${whereMia}"conteiner/miacalc $parametros
  else
    menuajuda ;
  fi
}
##################################### MAIN #####################################
# Parâmetros de reconhecimento de diretório onde está rodando a aplicação e
# parâmetros informados pelo usuário

getExecMiaPath && getParametros $* && getNome && getPath
getUsuario && getEditor && getBrowser
banner && echo -e "Olá $nome, bem vindo(a). ID: $usuario"
echo ""
interacoes "$1" "$parametros"
execFunctions "$1" "$parametros"
