#!/bin/bash
IP="$(echo $1|tr -d a-zA-z)"
test $(cut -d '.' -f1 <(echo $IP)) -lt "256" && a=$(cut -d '.' -f1 <(echo $IP))
test $(cut -d '.' -f2 <(echo $IP)) -lt "256" && b=$(cut -d '.' -f2 <(echo $IP))
test $(cut -d '.' -f3 <(echo $IP)) -lt "256" && c=$(cut -d '.' -f3 <(echo $IP))
test $(cut -d '.' -f4 <(echo $IP)) -lt "256" && d=$(cut -d '.' -f4 <(echo $IP))

if [[ "$a" != "" ]] && [[ "$b" != "" ]] && [[ "$c" != "" ]] &&[[ "$d" != "" ]]; then
	validateIP="$a.$b.$c.$d"
fi

echo $validateIP
