#!/bin/bash

user="$1"
echo -e "\033[01mUso: mia [função] ... {argumentos ou arquivos}\033[0m"
echo -e "\033[01m\nFunções para Pentest, FingerPrint e Footprint:\033[0m
Parâmetros de uso:
footprint, scan
\tRealiza um scan intenso em hosts e domínios, trazendo o maior número de informações
\tem um arquivo XML, padrão NMAP com a paleta de cores alterada. Tema 'Dark'.
\033[01m\nFunções Misc:\033[0m
Parâmetros de uso:
ola, help:
\tChama esse menu de ajuda.
compare, hash:
\tVerifica a integridade do arquivo através de hashs. Copie e cole a hash recebida
\tna página de download e confira se seu arquivo está integro ou não.
cara, coroa:
\tInforma aleatoriamente cara ou coroa para tomada de decisões.
cep, localiza:
\tRetorna informações sobre o CEP informado(via: postmon.com.br).
mia, install:
\tRealiza a instalação de mia para dentro do sistema Linux(em /usr/bin).
inverte, reverso:
\tInverte toda a string informada, onde a primeira vira a última, segunda vira
\ta penúltima...Similar ao 'rev', porém para strings.
rename, extensao
\tTroca a extensão de arquivos em um diretório, recursivamente.
tempo, data
\tMostra informações temporária sobre seu localhost, incluindo tempo
\tatravés do TCP TimeStamp (hping3)
cria, create
\tCria um arquivo com a extensão passada. De acordo com a extensão, M.I.A irá
\tgerar um código específico para aquela extensão do arquivo.

\033[01m\nFunções de Rede e configuração de servidores:\033[0m
Parâmetros de uso:
wan, ipext:
\tRetorna o IP externo, caso esteja conectado.
lan, ip:
\tRetorna o IP local, caso esteja conectado.
arp, arpfix:
\tFixa o gateway atual na tabela arp, evitando ataques man in the middle
swap, swappiness
\tAltera o swappiness de seu localhost para o número passado
\t*quanto menor o swappiness, maior será o uso da memória
\t*primária para operações
sql, database
\tRecupera a senha do MySQL/MariaDB via systemctl
macchange, spoof
\tAltera o 'MAC Address' de uma interface de rede.
mac, macsearch
\tBusca um endereço MAC ou Fabricante de drivers de rede.

\033[01mComandos em padrão POSIX:\033[0m
Parâmetros de uso:
-b, --browser
\tAltera o navegador padrão que M.I.A irá utilizar
-c, --config
\tMostra as configurações atuais do arquivo 'consciencia.conf'
-e, --editor
\tAltera o editor de texto padrão que M.I.A irá utilizar
-n, --nome
\tAltera o nome que M.I.A chamará em suas mensagens"
exit
